name: Keena
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17528
title: KEENA Secret Messages
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201f1b'
    - '#47484a'
    - '#e2e2e4'
    - '#67686c'
    - '#b0b3b8'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
