name: Keena
favicon: null
layout_spectrum: 0.49188
typography_spectrum: 0.52
title: AWAKEN YOUR WILD SOUL with Keena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0d9ed'
    - '#ee2e2f'
    - '#fb6a79'
    - '#278a6f'
    - '#510e0c'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
