name: Keena
favicon: null
layout_spectrum: 0.8471426633186638
typography_spectrum: 0.1467490999493748
title: Awaken Your Wild Soul
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfdfe'
    - '#292a46'
    - '#c0d3fc'
    - '#81769e'
    - '#27598b'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
