name: Keena
favicon: null
layout_spectrum: 0.42208
typography_spectrum: 0.52
title: AWAKEN YOUR WILD SOUL with Keena
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71c71e'
    - '#bd1153'
    - '#0e7786'
    - '#db7217'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
